# -*- coding: utf-8 -*-
"""CRORIS-network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hB72kmtDT38FBkTPh2K_m8161Z6rJCTf
"""

!pip install psycopg2
!pip install networkx
import psycopg2 as ps
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')
drive_path = '/content/drive/My Drive/croris/'

df_response = pd.read_csv(drive_path+'CRORIS_df_response.csv', index_col=0) 
df_ustanova = pd.read_csv(drive_path+'CRORIS_df_ustanova.csv', index_col=0) 
df_osoba = pd.read_csv(drive_path+'CRORIS_df_osoba.csv', index_col=0) 
df_projekt = pd.read_csv(drive_path+'CRORIS_df_projekt.csv', index_col=0) 
df_financijer = pd.read_csv(drive_path+'CRORIS_df_financijer.csv', index_col=0) 
df_osoba_projekt = pd.read_csv(drive_path+'CRORIS_df_osoba_projekt.csv', index_col=0) 
df_projekt_financijer = pd.read_csv(drive_path+'CRORIS_df_projekt_financijer.csv', index_col=0) 
df_projekt_tip = pd.read_csv(drive_path+'CRORIS_df_projekt_tip.csv', index_col=0) 
df_projekt_ustanova = pd.read_csv(drive_path+'CRORIS_df_projekt_ustanova.csv', index_col=0)

df_osoba_projekt

G = nx.Graph()

G.edges(data=True)

for index, row in df_osoba_projekt.iterrows():
  G.add_node(row[0])
  print(row[0])

  c=0
  for i, r in df_osoba_projekt.iterrows():
    if r[1] == row[1]:
      if r[0] != row[0]:
        G.add_edge(row[0], r[0])
        c += 1
  print('Index: '+index+'; Osoba: '+row[0]+'; Projekt: '+row[1]+'; Broj veza: '+str(c))

nx.draw_networkx(G)
plt.show()